# 画像サイズ (TTAやリサイズで使用)
img_size: 1000

# バッチサイズ (画像が大きいので小さめに)
batch_size: 1
num_workers: 2

# アンサンブル設定
n_folds: 5 # 0~4のモデルを使用

# 予測対象のカラム名 (3つ)
train_target_cols:
  - "Dry_Total_g"
  - "GDM_g"
  - "Dry_Green_g"

# 最終的な提出カラム名 (5つ)
all_target_cols:
  - "Dry_Green_g"
  - "Dry_Dead_g"
  - "Dry_Clover_g"
  - "GDM_g"
  - "Dry_Total_g"
